# Generated by Django 3.2.8 on 2021-10-11 11:43

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('Best Food', 'Best Food'), ('Best Food', 'Best Food'), ('Best Food', 'Best Food'), ('Best Food', 'Best Food'), ('Food', 'Food')], max_length=50),
        ),
    ]
