# Generated by Django 3.1.3 on 2021-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20211023_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
