# Generated by Django 3.2.8 on 2021-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_food_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('Indian Food', 'Indian Food'), ('South Food', 'South Food'), ('Gujarati Food', 'Gujarati Food'), ('PunjabiFood', 'PunjabiFood'), ('Food', 'Food')], max_length=50),
        ),
    ]
