# Generated by Django 3.2.8 on 2021-10-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_food_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sale_price',
        ),
    ]
