# Generated by Django 3.2.8 on 2021-10-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20211012_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
